### ISSUE TITLE
Congrats on your first github repo! 

### ISSUE THREAD

**Issue by arscan** [cclemente/test-repo#1]
:trophy: :trophy: :trophy: :trophy: :trophy: :trophy: :trophy: :trophy:

**Comment by cclemente** [comment]
Thanks mate! Hope you dont mind me stealing some of your code to play with!

**Comment by arscan** [comment]
Its up here to be played with bro :)  Lemme know if you have any questions.

I think that arscan.github.com repo needs to be gutted though... lots of dead stuff in there that I didn't bother to delete when I last redesigned it.
